### ISSUE TITLE
Can't create the fixture

### ISSUE THREAD

**Issue by dario86** [cakephp/elastic-search#117]
With this command 
`bin/cake bake fixture Agents --table agents -c elastic -p Agents --schema -v`

I get this error:

```
Exception: Call to undefined method Cake\ElasticSearch\Datasource\SchemaCollection::describe() in [/home/dario/www/dario.local/vendor/cakephp/bake/src/Shell/Task/FixtureTask.php, line 178]
2017-01-25 14:39:30 Error: [Error] Call to undefined method Cake\ElasticSearch\Datasource\SchemaCollection::describe()
Stack Trace:
#0 /home/dario/www/dario.local/vendor/cakephp/bake/src/Shell/Task/FixtureTask.php(123): Bake\Shell\Task\FixtureTask->bake('Agents', 'agents')
#1 [internal function]: Bake\Shell\Task\FixtureTask->main('Agents')
#2 /home/dario/www/dario.local/vendor/cakephp/cakephp/src/Console/Shell.php(472): call_user_func_array(Array, Array)
#3 /home/dario/www/dario.local/vendor/cakephp/cakephp/src/Console/Shell.php(465): Cake\Console\Shell->runCommand(Array, false, Array)
#4 /home/dario/www/dario.local/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(227): Cake\Console\Shell->runCommand(Array, true, Array)
#5 /home/dario/www/dario.local/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(182): Cake\Console\ShellDispatcher->_dispatch(Array)
#6 /home/dario/www/dario.local/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(128): Cake\Console\ShellDispatcher->dispatch(Array)
#7 /home/dario/www/dario.local/bin/cake.php(20): Cake\Console\ShellDispatcher::run(Array)
#8 {main}
```

I'm using Elasticsearch 2.3.1, CakePhp 3.3.12 and cakephp/elastic-search 1.0.x-dev

**Comment by markstory** [comment]
At this point in time fixture generation is not supported by ElasticSearch. You'll have to create your fixture by hand for now.
