### ISSUE TITLE
null

### ISSUE THREAD

**Issue by SparkyRih** [cakephp/elastic-search#254]
Not sure if I post this in the right, but since I'm running CakePHP.

So I'm getting this error: `Exception: null in [/var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php, line 636]`

While trying to do:
```php
$this->params = [];
$this->params["index"] = $index;

if (!$this->client->indices()->exists($this->params))
{
```

The reason why I post this here is because this piece of code worked perfectly fine before?

I'm running:
cakephp/cakephp                      3.9.8
cakephp/elastic-search               2.0.2
elasticsearch/elasticsearch          v6.7.2 
Elasticsearch: 7.10

Stack trace
```
Exception: null in [/var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php, line 636]
2021-03-11 17:03:39 Error: [Elasticsearch\Common\Exceptions\BadRequest400Exception] null in /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php on line 636
Stack Trace:
#0 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(295): Elasticsearch\Connections\Connection->process4xxError(Array, Array, Array)
#1 /var/www/html/vendor/react/promise/src/FulfilledPromise.php(28): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array)
#2 /var/www/html/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#3 /var/www/html/vendor/guzzlehttp/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#4 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(315): GuzzleHttp\Ring\Core::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
#5 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(187): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array, Object(Elasticsearch\Connections\Connection), Object(Elasticsearch\Transport), Array)
#6 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(112): Elasticsearch\Connections\Connection->performRequest('HEAD', '/IndexName', Array, NULL, Array, Object(Elasticsearch\Transport))
#7 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(262): Elasticsearch\Transport->performRequest('HEAD', '/IndexName', Array, NULL, Array)
#8 /var/www/html/vendor/react/promise/src/FulfilledPromise.php(28): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array)
#9 /var/www/html/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#10 /var/www/html/vendor/guzzlehttp/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#11 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(315): GuzzleHttp\Ring\Core::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
#12 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(187): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array, Object(Elasticsearch\Connections\Connection), Object(Elasticsearch\Transport), Array)
#13 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(112): Elasticsearch\Connections\Connection->performRequest('HEAD', '/IndexNames_da', Array, NULL, Array, Object(Elasticsearch\Transport))
#14 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(262): Elasticsearch\Transport->performRequest('HEAD', '/IndexName, Array, NULL, Array)
#15 /var/www/html/vendor/react/promise/src/FulfilledPromise.php(28): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array)
#16 /var/www/html/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#17 /var/www/html/vendor/guzzlehttp/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#18 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(315): GuzzleHttp\Ring\Core::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
#19 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(187): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array, Object(Elasticsearch\Connections\Connection), Object(Elasticsearch\Transport), Array)
#20 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(112): Elasticsearch\Connections\Connection->performRequest('HEAD', '/IndexName', Array, NULL, Array, Object(Elasticsearch\Transport))
#21 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(262): Elasticsearch\Transport->performRequest('HEAD', '/IndexName', Array, NULL, Array)
#22 /var/www/html/vendor/react/promise/src/FulfilledPromise.php(28): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array)
#23 /var/www/html/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#24 /var/www/html/vendor/guzzlehttp/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#25 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(315): GuzzleHttp\Ring\Core::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
#26 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(187): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array, Object(Elasticsearch\Connections\Connection), Object(Elasticsearch\Transport), Array)
#27 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(112): Elasticsearch\Connections\Connection->performRequest('HEAD', '/IndexName', Array, NULL, Array, Object(Elasticsearch\Transport))
#28 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/BooleanRequestWrapper.php(40): Elasticsearch\Transport->performRequest('HEAD', '/IndexName', Array, NULL, Array)
#29 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IndicesNamespace.php(40): Elasticsearch\Namespaces\BooleanRequestWrapper::performRequest(Object(Elasticsearch\Endpoints\Indices\Exists), Object(Elasticsearch\Transport))
#30 /var/www/html/src/Repository/Elasticsearch/BaseElasticsearchRepository.php(26): Elasticsearch\Namespaces\IndicesNamespace->exists(Array)
#31 /var/www/html/src/Service/***Service.php(255): App\Repository\Elasticsearch\BaseElasticsearchRepository->SetIndex('IndexName')
#32 /var/www/html/src/Service/***Service.php(132): App\Service\***Service->SetIndex(13)
#33 /var/www/html/src/Service/TaskService.php(32): App\Service\***Service->Get***(14, 13, 210, 0, 12)
#34 /var/www/html/src/Shell/RunTasksShell.php(14): App\Service\TaskService->run(508)
#35 /var/www/html/vendor/cakephp/cakephp/src/Console/Shell.php(531): App\Shell\RunTasksShell->main()
#36 /var/www/html/vendor/cakephp/cakephp/src/Console/CommandRunner.php(384): Cake\Console\Shell->runCommand(Array, true)
#37 /var/www/html/vendor/cakephp/cakephp/src/Console/CommandRunner.php(162): Cake\Console\CommandRunner->runShell(Object(App\Shell\RunTasksShell), Array)
#38 /var/www/html/bin/cake.php(12): Cake\Console\CommandRunner->run(Array)
#39 {main}
```

**Comment by CauanCabral** [comment]
Hi,

> I'm running:
> cakephp/cakephp 3.9.8
> cakephp/elastic-search 2.0.2
> elasticsearch/elasticsearch v6.7.2
> Elasticsearch: 7.10

Theres no support for `Elasticsearch 7.x` for now. We have a open PR #252 to address this.

But I don't know if thats your problem. Did you made a `datasource` configuration for your elasticsearch connection into `app_local.php` (or `app.php`)?

**Comment by SparkyRih** [comment]
Yes, I've configured everything properly in the `config/app.php`, when I stop the elasticsearch service, I get a nice message telling me that there are no alive nodes.
